# ==============================================================================
# Hospital Information Assistance — Chatbot Router
# ==============================================================================
# WHY THIS FILE EXISTS:
#   Defines the HTTP endpoints for interacting with the AI chatbot.
#   It connects client requests to the AIService layer, which uses LangChain
#   and Groq to generate responses with context memory.
#
# ENDPOINTS:
#   POST   /chat                                      → Send a chat message (user)
#   POST   /chat/sessions                             → Create a new chat session
#   GET    /chat/sessions                             → List all user chat sessions
#   GET    /chat/sessions/{session_id}/history        → Get full history for a session
#   DELETE /chat/sessions/{session_id}/clear          → Clear memory of a session
# ==============================================================================

from fastapi import APIRouter, Depends, status, Query
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Optional

from app.database import get_db
from app.dependencies import get_current_user, get_pagination_params
from app.models.user import User
from app.schemas.chatbot import (
    ChatRequest,
    ChatResponse,
    SessionCreateRequest,
    SessionResponse,
    SessionListResponse,
    ChatHistoryResponse
)
from app.services.ai_service import AIService

# Create the router — all routes here will be prefixed with /chat (registered in main.py)
router = APIRouter()


# ==============================================================================
# SEND CHAT MESSAGE
# Method: POST
# Path:   /chat
# Access: Protected (any logged-in user)
# ==============================================================================
@router.post(
    "/",
    response_model=ChatResponse,
    status_code=status.HTTP_200_OK,
    summary="Send a message to the AI chatbot",
    description="""
    Sends a message to the AI assistant. 
    Requires a `session_id` (typically a UUID generated by the frontend).
    Reusing the same `session_id` allows the AI to remember the chat history.
    """
)
async def send_message(
    chat_request: ChatRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> ChatResponse:
    """
    Send a message to the AI chatbot.

    Authentication Required: Yes (any logged-in user)

    Request Body:
    - session_id: Unique string to track conversation memory (UUID recommended)
    - message: The user's query/message text

    Returns:
    - success: True/False
    - session_id: The session ID
    - user_message: Echoes the input message
    - ai_response: The response text generated by Groq LLM
    - message_count: Total messages in the session
    - timestamp: When the message was processed

    Errors:
    - 400 Bad Request: Empty message
    - 401 Unauthorized: Invalid or missing token
    - 500 Internal Server Error: AI service error
    """
    return await AIService.send_message(
        db=db,
        chat_request=chat_request,
        current_user=current_user
    )


# ==============================================================================
# CREATE A CHAT SESSION
# Method: POST
# Path:   /chat/sessions
# Access: Protected (any logged-in user)
# ==============================================================================
@router.post(
    "/sessions",
    response_model=SessionResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create a new named chat session",
    description="""
    Explicitly creates a new chat session with a custom title.
    If no `session_id` is provided, a UUID is automatically generated.
    """
)
async def create_session(
    session_data: SessionCreateRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> SessionResponse:
    """
    Create a new chat session.

    Authentication Required: Yes (any logged-in user)

    Request Body (optional):
    - session_id: Pre-defined unique session string
    - title: Initial title for the session

    Returns:
    - Session details including ID, title, and timestamps
    """
    return await AIService.create_session(
        db=db,
        session_data=session_data,
        current_user=current_user
    )


# ==============================================================================
# GET USER CHAT SESSIONS
# Method: GET
# Path:   /chat/sessions
# Access: Protected (any logged-in user)
# ==============================================================================
@router.get(
    "/sessions",
    response_model=SessionListResponse,
    status_code=status.HTTP_200_OK,
    summary="List my chat sessions",
    description="Returns a paginated list of all chat sessions belonging to the logged-in user."
)
async def list_sessions(
    pagination: dict = Depends(get_pagination_params),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> SessionListResponse:
    """
    Get the logged-in user's chat sessions (for history sidebar).

    Authentication Required: Yes (any logged-in user)

    Query Parameters:
    - skip: Pagination offset
    - limit: Max sessions per page

    Returns:
    - total: Total count of sessions owned by this user
    - sessions: List of session detail objects
    """
    return await AIService.get_my_sessions(
        db=db,
        current_user=current_user,
        skip=pagination["skip"],
        limit=pagination["limit"]
    )


# ==============================================================================
# GET CHAT SESSION HISTORY
# Method: GET
# Path:   /chat/sessions/{session_id}/history
# Access: Protected (session owner only)
# ==============================================================================
@router.get(
    "/sessions/{session_id}/history",
    response_model=ChatHistoryResponse,
    status_code=status.HTTP_200_OK,
    summary="Get full conversation history for a session",
    description="Returns all previous human and AI messages for a given session."
)
async def get_session_history_route(
    session_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> ChatHistoryResponse:
    """
    Retrieve message history logs for a session.

    Authentication Required: Yes (must own the session)

    Path Parameters:
    - session_id: The session ID to view history for

    Returns:
    - session_id, title, list of messages (role + content), and count

    Errors:
    - 404 Not Found: Session does not exist or doesn't belong to the user
    """
    return await AIService.get_chat_history(
        db=db,
        session_id=session_id,
        current_user=current_user
    )


# ==============================================================================
# CLEAR CHAT SESSION HISTORY
# Method: DELETE
# Path:   /chat/sessions/{session_id}/clear
# Access: Protected (session owner only)
# ==============================================================================
@router.delete(
    "/sessions/{session_id}/clear",
    status_code=status.HTTP_200_OK,
    summary="Clear conversation history memory",
    description="""
    Clears all messages from memory for this session. 
    The database session record itself is kept but reset to default values.
    """
)
async def clear_session_history(
    session_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> dict:
    """
    Clear history logs of a session.

    Authentication Required: Yes (must own the session)

    Path Parameters:
    - session_id: The session ID to reset memory for

    Returns:
    - message: Confirmation message

    Errors:
    - 404 Not Found: Session not found
    """
    return await AIService.clear_session_history(
        db=db,
        session_id=session_id,
        current_user=current_user
    )
